language: php

php:
  - '7.3'
  - '7.2'
  - '7.1'

env:
  matrix:
  - DEPENDENCIES_LOWEST=0
  - DEPENDENCIES_LOWEST=1

install:
  - composer install
  - if [ $DEPENDENCIES_LOWEST -eq 1 ]; then composer update --prefer-lowest; fi

before_script:
  - composer global require phpunit/phpunit ^7.5

script: $(composer config home)/vendor/bin/phpunit
